### ISSUE TITLE
Debugging/improving error checking

### ISSUE THREAD

**Issue by salvadord** [suny-downstate-medical-center/netpyne#238]
got the following with cfg.checkError = True but the model actually runs ok:

```
ERROR: Value specified is not an integer.
ERROR: Value specified is not an integer.
ERROR: Value specified is not an integer.
Traceback (most recent call last):
  File "/u/salvadord/Documents/ISB/Models/netpyne_repo/netpyne/tests/tests.py", line 1758, in execRunTests
    self.testTypeObj.testExistsInDict (  paramValues[testObj.testParameterValue][testObj.testParameterValue1],  eval(testObj.compareDict), testObj.testParameterValue1)
  File "/u/salvadord/Documents/ISB/Models/netpyne_repo/netpyne/tests/tests.py", line 118, in testExistsInDict
    assert existsInDict is True, " Value " + str(val) + "exists in dictionary " + str(params) + "."
NameError: global name 'params' is not defined
WARNING : cellModel does not match the cellModel specified in pop parameters.
```
- check why get error: 'params' is not defined
- the ERROR and the WARNING don't include info about in what structure it happened

**Comment by salvadord** [comment]
Add error checking for simConfig -- including recordTraces, analysis/plots etc
