### ISSUE TITLE
import neuroML error. -->  nmlHandler == None type

### ISSUE THREAD

**Issue by rodriguez-facundo** [suny-downstate-medical-center/netpyne#368]
I'm trying to export a model to neuroML and import it back into netpyne. Probably is just a silly mistake, but I am getting an error message when importing back.

My netpyne network is this one:

# Script
`from netpyne import specs, sim
`
## Network parameters
`netParams = specs.NetParams()`

## Population parameters
```
netParams.popParams['S'] = {'cellType': 'PYR', 'numCells': 20, 'cellModel': 'HH'}
netParams.popParams['M'] = {'cellType': 'PYR', 'numCells': 20, 'cellModel': 'HH'} 

```
## Cell property rules
```
cellRule = {'conds': {'cellType': 'PYR'},  'secs': {}}
cellRule['secs']['soma'] = {'geom': {}, 'mechs': {}}
cellRule['secs']['soma']['geom'] = {'diam': 18.8, 'L': 18.8, 'Ra': 123.0}
cellRule['secs']['soma']['mechs']['hh'] = {'gnabar': 0.12, 'gkbar': 0.036, 'gl': 0.003, 'el': -70}
cellRule['secs']['dend'] = {'geom': {}, 'topol': {}, 'mechs': {}}
cellRule['secs']['dend']['geom'] = {'diam': 5.0, 'L': 150.0, 'Ra': 150.0, 'cm': 1}
cellRule['secs']['dend']['topol'] = {'parentSec': 'soma', 'parentX': 1.0, 'childX': 0}
cellRule['secs']['dend']['mechs']['pas'] = {'g': 0.0000357, 'e': -70}
netParams.cellParams['PYRrule'] = cellRule

```

## Synaptic mechanism parameters
`netParams.addSynMechParams('exc', {'mod': 'Exp2Syn', 'tau1': 1.0, 'tau2': 5.0, 'e': 0})`  
 

## Stimulation parameters
```
netParams.stimSourceParams['bkg'] = {'type': 'NetStim', 'rate': 10, 'noise': 0}
netParams.stimTargetParams['bkg->PYR'] = {'source': 'bkg', 'conds': {'cellType': 'PYR'}, 'weight': 0.01, 'delay': 5, 'synMech': 'exc'}
```

## Cell connectivity rules
```
netParams.connParams['S->M'] = {'preConds': {'pop': 'S'}, 'postConds': {'pop': 'M'},
	'probability': 0.5,
	'weight': 0.01,
	'delay': 5,
	'sec': 'dend',
	'loc': 1.0,
	'synMech': 'exc'}

```

## Simulation options
```
simConfig = specs.SimConfig()
simConfig.duration = 1*1e3 
simConfig.dt = 0.025
simConfig.verbose = False
simConfig.recordTraces = {'V_soma':{'sec':'soma','loc':0.5,'var':'v'}} 
simConfig.recordStep = 1 
simConfig.filename = 'model_output'
simConfig.savePickle = False

```
## Create network and run simulation
```
sim.createSimulateAnalyze(netParams = netParams, simConfig = simConfig)    
sim.exportNeuroML2('my_file', specs.SimConfig())

```
------
Then I try to import with this script:
## Import Script
```
from netpyne import sim, specs
sim.initialize()
sim.importNeuroML2('LEMS_my_file', simConfig=specs.SimConfig(), simulate=False, analyze=False)
```
--------
and the error I get is this one:
```
Importing NeuroML 2 network from: LEMS_my_file

Creating network of 0 cell populations on 1 hosts...
  Number of cells on node 0: 0 
  Done; cell creation time = 0.00 s.
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    sim.importNeuroML2('LEMS_my_file', simConfig=specs.SimConfig(), simulate=False, analyze=False)
  File "/Users/fr/Desktop/NetPyNE-UI3/netpyne/netpyne/neuromlFuncs.py", line 1361, in importNeuroML2
    for proj_id in list(nmlHandler.projection_infos.keys()):
AttributeError: 'NoneType' object has no attribute 'projection_infos'
```

**Comment by jackdwyer** [comment]
What is the file extension of the import file? 
Looking at https://github.com/Neurosim-lab/netpyne/blob/89465672a6e3972a3613504bd9f07d1a85f13bb3/netpyne/conversion/neuromlFormat.py#L1307
https://github.com/Neurosim-lab/netpyne/blob/89465672a6e3972a3613504bd9f07d1a85f13bb3/netpyne/conversion/neuromlFormat.py#L1311
https://github.com/Neurosim-lab/netpyne/blob/89465672a6e3972a3613504bd9f07d1a85f13bb3/netpyne/conversion/neuromlFormat.py#L1332
`nmlHandler` will be set to `None` if your file extension is not `.nml` or `.h5`
